### ISSUE TITLE
Can't connect to Reachy using USB2AX

### ISSUE THREAD

**Issue by Net-Mist** [pollen-robotics/reachy-2019#30]
I tried to connect to Reachy using the commands:

```python
from reachy import Reachy, parts
PORT = "/dev/ttypACM0"
reachy = Reachy(
    right_arm=parts.arm.RightArm(
        luos_port=PORT,
        hand='force_gripper',
    ),
)
```

but I get the error:
```
Traceback (most recent call last):
  File "move_and_grap.py", line 8, in <module>
    hand='force_gripper',
  File "/home/seb/workspace/reachy/software/reachy/parts/arm.py", line 194, in __init__
    hand=hand)
  File "/home/seb/workspace/reachy/software/reachy/parts/arm.py", line 42, in __init__
    self.luos_io = SharedLuosIO.with_gate(f'r_{side}_arm', luos_port)
  File "/home/seb/workspace/reachy/software/reachy/io/luos.py", line 86, in with_gate
    return cls(port_template)
  File "/home/seb/workspace/reachy/software/reachy/io/luos.py", line 45, in __init__
    io = attempt_luos_connection(luos_port)
  File "/home/seb/workspace/reachy/software/reachy/io/luos.py", line 15, in attempt_luos_connection
    io = LuosIO(port, log_conf='')
  File "/home/seb/.local/lib/python3.6/site-packages/pyluos/robot.py", line 60, in __init__
    *args, **kwargs)
  File "/home/seb/.local/lib/python3.6/site-packages/pyluos/io/__init__.py", line 56, in io_from_host
    raise ValueError('No corresponding IO found (among {}).'.format(discover_hosts))
ValueError: No corresponding IO found (among <function discover_hosts at 0x7fbbb23f4378>).

```

My versions :
  - Ubuntu 18.04
  - Python 3.6.8
  - reachy package : -e git+git@github.com:pollen-robotics/reachy.git@d98b292318684f0808fca848dbb4283cfd4e3c43#egg=reachy&subdirectory=software (installed today from github)

The file /dev/ttyACM0 exists when the robot is connected to the computer

Do you have an idea of what's going on ?

Thank you

**Comment by pierre-rouanet** [comment]
Hi @Net-Mist,

It seems you are trying to connect using USB2AX (the old version). This device is no longer maintain and will thus no longer be supported by the new version of Reachy.

The documentation is still WIP and I'll definitely add this question in the FAQ!

Do not hesitate to contact me or the rest of the team so we can arrange upgrading your Reachy to the newest version.
