### ISSUE TITLE
ModuleNotFoundError: No module named 'pyluos.modules'

### ISSUE THREAD

**Issue by ilbertt** [pollen-robotics/reachy-2019#67]
**Describe the bug**
Missing module _pyluos.modules_ when importing reachy in Python.

**To Reproduce**
1. `pip3 install reachy`
2. run `python3` from terminal (Python version: **3.8.5**)
3. `import reachy` or `from reachy import parts, Reachy`

**Expected behavior**
Clear import with no error.

**Screenshots**
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import reachy

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/.local/lib/python3.8/site-packages/reachy/__init__.py", line 11, in <module>
    from .reachy import Reachy  # noqa: F401
  File "$HOME/.local/lib/python3.8/site-packages/reachy/reachy.py", line 9, in <module>
    from .parts import LeftArm, RightArm, Head
  File "$HOME/.local/lib/python3.8/site-packages/reachy/parts/__init__.py", line 10, in <module>
    from .arm import LeftArm, RightArm # noqa
  File "$HOME/.local/lib/python3.8/site-packages/reachy/parts/arm.py", line 13, in <module>
    from .hand import LeftEmptyHand, RightEmptyHand, LeftForceGripper, RightForceGripper, OrbitaWrist
  File "$HOME/.local/lib/python3.8/site-packages/reachy/parts/hand.py", line 15, in <module>
    from .part import ReachyPart
  File "$HOME/.local/lib/python3.8/site-packages/reachy/parts/part.py", line 8, in <module>
    from ..io import IO, luos, ws
  File "$HOME/.local/lib/python3.8/site-packages/reachy/io/luos.py", line 8, in <module>
    from pyluos.modules import DynamixelMotor
ModuleNotFoundError: No module named 'pyluos.modules'
>>>
```

**Environment (please complete the following information):**
 - Running on my PC
 - OS: Ubuntu 20.04
 - Python Version 3.8.5

**Comment by pierre-rouanet** [comment]
Hi Luca,

Thx for reporting it. It was actually fixed in https://github.com/pollen-robotics/reachy/commit/6c5095c9a6648c49aa74d8996d9f09453f9305a5 (See #66) but was not built as a release.

It should be ok now! Make sure you are using reachy 1.3.2 (currently latest version on pypi).
